# Generated by Django 5.1.7 on 2025-03-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock_vente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produitcommande',
            options={},
        ),
    ]
