# Generated by Django 5.1.7 on 2025-03-24 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock_vente', '0002_alter_produitcommande_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvement',
            options={'ordering': ['-date'], 'verbose_name': 'Mouvement de stock', 'verbose_name_plural': 'Mouvements de stock'},
        ),
        migrations.AddField(
            model_name='mouvement',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock_vente.commandes'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='gestion_stock_vente.produitcommande'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10),
        ),
    ]
